### PR TITLE
feat: update icon imports and navbar structure, disable changing of writedir

### PR DESCRIPTION
**Pull request by JonathanTurnock**
- Replace Vsc icons with Fa icons for consistency
- Rearrange navbar items and introduce navbarSecondary
- Add Flex component for better layout management in app.navbar.tsx
- Remove option to change the writedir

This pull request includes several changes to the `src/main/router.ts`, `src/renderer/src/app.navbar.tsx`, `src/renderer/src/config.tsx`, and `src/renderer/src/pages/settings.page.tsx` files to add new functionalities and improve the user interface. The most important changes include the addition of a new service, updates to the navigation bar, and enhancements to the settings page.

### New Service Addition:
* [`src/main/router.ts`](diffhunk://#diff-7bebe260784b73ff7c756e76186a68fc41c892698994e0dedcdb77e20c90143bR15): Imported `WriteDirectoryService` and added a new `openWriteDirInExplorer` mutation to open the write directory in the file explorer. [[1]](diffhunk://#diff-7bebe260784b73ff7c756e76186a68fc41c892698994e0dedcdb77e20c90143bR15) [[2]](diffhunk://#diff-7bebe260784b73ff7c756e76186a68fc41c892698994e0dedcdb77e20c90143bR65-R68)

### Navigation Bar Updates:
* [`src/renderer/src/app.navbar.tsx`](diffhunk://#diff-9c33fdd5aa8477a5cea7e9c0c01ab58630e8958dd72d50cebe6f3a00f7ac2122L1-R1): Added `Flex` component to wrap navigation items and included a secondary navigation section. [[1]](diffhunk://#diff-9c33fdd5aa8477a5cea7e9c0c01ab58630e8958dd72d50cebe6f3a00f7ac2122L1-R1) [[2]](diffhunk://#diff-9c33fdd5aa8477a5cea7e9c0c01ab58630e8958dd72d50cebe6f3a00f7ac2122R12-R15)
* [`src/renderer/src/config.tsx`](diffhunk://#diff-c0892974f9377a2da6b973caddd74bbcc85dc9eab463c7b180c1153689331ffeL1-L48): Replaced `react-icons/vsc` icons with `react-icons/fa6` icons and updated the configuration to include a secondary navigation bar. ([src/renderer/src/config.tsxL1-L48](diffhunk://#diff-c0892974f9377a2da6b973caddd74bbcc85dc9eab463c7b180c1153689331ffeL1-L48), Ff87bfecL9R9)

### Settings Page Enhancements:
* [`src/renderer/src/pages/settings.page.tsx`](diffhunk://#diff-6e43e83519068d46f852301bbb693a9004afbf46aa7f907e688271acff6de29aL16-L43): Removed the `Title` component and the `writeDir` configuration from the `Configurables` component and added a new section for the write directory with an alert for failures. [[1]](diffhunk://#diff-6e43e83519068d46f852301bbb693a9004afbf46aa7f907e688271acff6de29aL16-L43) [[2]](diffhunk://#diff-6e43e83519068d46f852301bbb693a9004afbf46aa7f907e688271acff6de29aR79-L113) [[3]](diffhunk://#diff-6e43e83519068d46f852301bbb693a9004afbf46aa7f907e688271acff6de29aL134-R147)

### CODE REVIEW

**Comment by JonathanTurnock** [comment]
image

**Comment by john681611** [comment]
My main concern here is removing the ability to select the write location. I'd personally want to put it on a separate drive. If I had a lot of mods maybe a dedicated drive is something I'd use. One of the biggest messes is DCS forcing mods onto one folder on the C drive

**Comment by JonathanTurnock** [comment]
I agree I think its a really important feature but nothing is tested and working for it right now so if someone did change it after a few subscriptions I think it might break.

Would love to re-introduce it but only as a developed feature with enough confidence it doesn't leave anything broken.

**Review by john681611 — APPROVED** [review]

**Comment by john681611** [comment]
I'd expect it to be a major feature request fairly soon.

**Pull request merged**
